import { ChallengeRow, NoticeRow, UserStudyStatRow, VerseRow } from './types';

export const VERSE_ITEMS_DATA: VerseRow[] = [
  {
    id: 1,
    book: '요한계시록',
    chapter: 1,
    verse: 3,
    reference: '계 1:3',
    text: '이 예언의 말씀을 읽는 자와 듣는 자와 그 가운데에 기록한 것을 지키는 자들이 복이 있나니 때가 가까움이라',
    category: '예언의 복',
    stage: '암송완료',
    accuracyRate: 96,
    reviewCycle: '1·3·7·14일 주기',
    nextReviewDate: '2026-07-23',
    createdAt: '2026-06-01',
  },
  {
    id: 2,
    book: '요한계시록',
    chapter: 1,
    verse: 4,
    reference: '계 1:4',
    text: '요한은 아시아에 있는 일곱 교회에 편지하노니 이제도 계시고 전에도 계셨고 장차 오실 이와 그 보좌 앞에 있는 일곱 영과',
    category: '문안 인사',
    stage: '4단계',
    accuracyRate: 88,
    reviewCycle: '1·3·7·14일 주기',
    nextReviewDate: '2026-07-23',
    createdAt: '2026-06-02',
  },
  {
    id: 3,
    book: '요한계시록',
    chapter: 1,
    verse: 5,
    reference: '계 1:5',
    text: '또 충성된 증인으로 죽은 자들 가운데에서 먼저 나시고 땅의 임금들의 머리가 되신 예수 그리스도로 말미암아 은혜와 평강이 너희에게 있기를 원하노라',
    category: '문안 인사',
    stage: '3단계(초성보기)',
    accuracyRate: 79,
    reviewCycle: '1·3·7·14일 주기',
    nextReviewDate: '2026-07-23',
    createdAt: '2026-06-02',
  },
  {
    id: 4,
    book: '요한계시록',
    chapter: 2,
    verse: 2,
    reference: '계 2:2',
    text: '내가 네 행위와 수고와 네 인내를 알고 또 악한 자들을 능히 참지 못하는 것과 자칭 사도라 하되 아닌 자들을 시험하여 그 거짓된 것을 네가 드러낸 것과',
    category: '에베소 교회',
    stage: '3단계(초성보기)',
    accuracyRate: 74,
    reviewCycle: '1·3·7·14일 주기',
    nextReviewDate: '2026-07-24',
    createdAt: '2026-06-10',
  },
  {
    id: 5,
    book: '요한계시록',
    chapter: 2,
    verse: 4,
    reference: '계 2:4',
    text: '그러나 너를 책망할 것이 있나니 너의 처음 사랑을 버렸느니라',
    category: '에베소 교회',
    stage: '3단계(초성보기)',
    accuracyRate: 84,
    reviewCycle: '1·3·7·14일 주기',
    nextReviewDate: '2026-07-24',
    createdAt: '2026-06-12',
  },
  {
    id: 6,
    book: '요한계시록',
    chapter: 2,
    verse: 5,
    reference: '계 2:5',
    text: '그러므로 어디서 떨어졌는지를 생각하고 회개하여 처음 행위를 가지라 그리하지 아니하면 내가 네게 가서 네 촛대를 그 자리에서 옮기리라',
    category: '에베소 교회',
    stage: '2단계',
    accuracyRate: 61,
    reviewCycle: '1·3·7·14일 주기',
    nextReviewDate: '2026-07-25',
    createdAt: '2026-06-14',
  },
  {
    id: 7,
    book: '요한계시록',
    chapter: 2,
    verse: 7,
    reference: '계 2:7',
    text: '귀 있는 자는 성령이 교회들에게 하시는 말씀을 들을지어다 이기는 그에게는 내가 하나님의 낙원에 있는 생명나무의 과실을 주어 먹게 하리라',
    category: '에베소 교회',
    stage: '1단계',
    accuracyRate: 42,
    reviewCycle: '1·3·7·14일 주기',
    nextReviewDate: '2026-07-26',
    createdAt: '2026-06-16',
  },
  {
    id: 8,
    book: '요한계시록',
    chapter: 2,
    verse: 10,
    reference: '계 2:10',
    text: '너는 장차 받을 고난을 두려워하지 말라 볼지어다 마귀가 장차 너희 가운데에서 몇 사람을 옥에 던져 시험을 받게 하리니 너희가 십 일 동안 환난을 받으리라 네가 죽도록 충성하라 그리하면 내가 생명의 관을 네게 주리라',
    category: '서머나 교회',
    stage: '1단계',
    accuracyRate: 30,
    reviewCycle: '1·3·7·14일 주기',
    nextReviewDate: '2026-07-27',
    createdAt: '2026-06-18',
  },
];

export const CHALLENGE_ITEMS_DATA: ChallengeRow[] = [
  {
    id: 1,
    title: '계시록 2장 완주 챌린지',
    description: '요한계시록 2장 전체 7개 절을 7일 안에 암송 완료하기',
    book: '요한계시록 2장',
    startDate: '2026-07-18',
    endDate: '2026-07-27',
    totalVerses: 7,
    completedVerses: 4,
    participantCount: 128,
    status: '진행중',
  },
  {
    id: 2,
    title: '7월 계시록 전체 챌린지',
    description: '7월 한 달간 요한계시록 1~3장 암송에 도전하는 전체 챌린지',
    book: '요한계시록 1~3장',
    startDate: '2026-07-01',
    endDate: '2026-07-31',
    totalVerses: 30,
    completedVerses: 12,
    participantCount: 512,
    status: '진행중',
  },
  {
    id: 3,
    title: '계시록 1장 완주 챌린지',
    description: '요한계시록 1장 전체 절 암송 완료하기',
    book: '요한계시록 1장',
    startDate: '2026-06-01',
    endDate: '2026-06-20',
    totalVerses: 20,
    completedVerses: 20,
    participantCount: 340,
    status: '종료',
  },
  {
    id: 4,
    title: '8월 서머나·버가모 챌린지',
    description: '요한계시록 2:8~17 서머나·버가모 교회 말씀 암송 챌린지',
    book: '요한계시록 2:8-17',
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    totalVerses: 10,
    completedVerses: 0,
    participantCount: 0,
    status: '예정',
  },
];

export const NOTICE_ITEMS_DATA: NoticeRow[] = [
  {
    id: 1,
    message: '7월 계시록 전체 챌린지가 시작되었습니다',
    linkPath: '/verse-app/challenge',
    isActive: true,
    createdAt: '2026-07-01',
  },
  {
    id: 2,
    message: '암송 정확도 채점 기준이 일부 개선되었습니다',
    linkPath: '/verse-app/study',
    isActive: true,
    createdAt: '2026-07-10',
  },
  {
    id: 3,
    message: '6월 계시록 1장 챌린지 결과가 발표되었습니다',
    linkPath: '/verse-app/challenge',
    isActive: false,
    createdAt: '2026-06-21',
  },
];

export const USER_STUDY_STATS_DATA: UserStudyStatRow[] = [
  {
    id: 1,
    name: '김은혜',
    email: 'grace.kim@example.com',
    progressRate: 31,
    accuracyRate: 84,
    completedVerseCount: 127,
    streakDays: 5,
    lastStudyDate: '2026-07-22',
  },
  {
    id: 2,
    name: '박요한',
    email: 'john.park@example.com',
    progressRate: 58,
    accuracyRate: 91,
    completedVerseCount: 214,
    streakDays: 12,
    lastStudyDate: '2026-07-22',
  },
  {
    id: 3,
    name: '이다윗',
    email: 'david.lee@example.com',
    progressRate: 12,
    accuracyRate: 67,
    completedVerseCount: 38,
    streakDays: 1,
    lastStudyDate: '2026-07-21',
  },
  {
    id: 4,
    name: '최마리아',
    email: 'maria.choi@example.com',
    progressRate: 74,
    accuracyRate: 95,
    completedVerseCount: 302,
    streakDays: 21,
    lastStudyDate: '2026-07-22',
  },
  {
    id: 5,
    name: '정베드로',
    email: 'peter.jung@example.com',
    progressRate: 4,
    accuracyRate: 40,
    completedVerseCount: 9,
    streakDays: 0,
    lastStudyDate: '2026-07-15',
  },
  {
    id: 6,
    name: '한사라',
    email: 'sarah.han@example.com',
    progressRate: 45,
    accuracyRate: 88,
    completedVerseCount: 168,
    streakDays: 8,
    lastStudyDate: '2026-07-22',
  },
];

export interface WeeklyStreakDay {
  label: string;
  completed: boolean;
}

export const WEEKLY_STREAK_DATA: WeeklyStreakDay[] = [
  { label: '월', completed: true },
  { label: '화', completed: true },
  { label: '수', completed: true },
  { label: '목', completed: false },
  { label: '금', completed: true },
  { label: '토', completed: true },
  { label: '일', completed: false },
];
