import { BookRow } from './types';

export const BOOK_ITEMS_DATA: BookRow[] = [
  {
    id: 1,
    title: '클린 코드',
    author: '로버트 C. 마틴',
    publisher: '인사이트',
    publishedDate: '2013-12-24',
    isbn: '978-89-6626-091-8',
    category: '프로그래밍',
    status: '대출가능',
    description: '읽기 쉽고 유지보수하기 좋은 코드를 작성하는 방법을 다루는 소프트웨어 장인 정신의 고전.',
    coverImage: '1.jpg',
  },
  {
    id: 2,
    title: '리팩터링 2판',
    author: '마틴 파울러',
    publisher: '한빛미디어',
    publishedDate: '2020-03-01',
    isbn: '978-89-6848-450-1',
    category: '프로그래밍',
    status: '대출중',
    description: '코드의 겉보기 동작을 바꾸지 않으면서 내부 구조를 개선하는 표준 리팩터링 기법을 정리한 책.',
    coverImage: '2.jpg',
  },
  {
    id: 3,
    title: '이펙티브 타입스크립트',
    author: '댄 반더캄',
    publisher: '인사이트',
    publishedDate: '2021-01-25',
    isbn: '978-89-6626-330-8',
    category: '프로그래밍',
    status: '대출가능',
    description: '타입스크립트를 더 안전하고 효율적으로 사용하기 위한 62가지 실전 가이드.',
    coverImage: '3.jpg',
  },
  {
    id: 4,
    title: '도메인 주도 설계',
    author: '에릭 에반스',
    publisher: '위키북스',
    publishedDate: '2011-04-01',
    isbn: '978-89-6626-097-0',
    category: '소프트웨어 설계',
    status: '대출중',
    description: '복잡한 비즈니스 도메인을 소프트웨어로 옮기기 위한 설계 방법론을 제시하는 DDD 원전.',
    coverImage: '4.jpg',
  },
  {
    id: 5,
    title: '실용주의 프로그래머',
    author: '데이비드 토머스, 앤드류 헌트',
    publisher: '인사이트',
    publishedDate: '2022-08-19',
    isbn: '978-89-6626-368-1',
    category: '프로그래밍',
    status: '대출가능',
    description: '20주년 기념판. 실용적인 사고와 태도로 더 나은 개발자가 되는 법을 담았다.',
    coverImage: '5.jpg',
  },
  {
    id: 6,
    title: '함께 자라기',
    author: '김창준',
    publisher: '인사이트',
    publishedDate: '2018-11-05',
    isbn: '978-89-6626-238-7',
    category: '애자일',
    status: '대출가능',
    description: '애자일과 학습에 대한 통찰을 담은, 함께 성장하는 팀을 만드는 방법에 관한 이야기.',
    coverImage: '6.jpg',
  },
  {
    id: 7,
    title: 'The DevOps Handbook',
    author: '진 킴 외',
    publisher: 'IT Revolution Press',
    publishedDate: '2016-10-06',
    isbn: '978-1-942788-00-3',
    category: 'DevOps',
    status: '대출가능',
    description: '고성과 조직이 개발과 운영을 통합해 속도와 안정성을 함께 달성하는 방법을 설명한다.',
    coverImage: '7.jpg',
  },
  {
    id: 8,
    title: '유닉스의 탄생',
    author: '브라이언 커니핸',
    publisher: '한빛미디어',
    publishedDate: '2020-06-15',
    isbn: '978-89-6848-484-6',
    category: '컴퓨터 역사',
    status: '대출중',
    description: '유닉스와 C 언어가 만들어진 벨 연구소의 이야기를 당사자의 시선으로 풀어낸 회고록.',
    coverImage: '8.jpg',
  },
  {
    id: 9,
    title: '데이터 중심 애플리케이션 설계',
    author: '마틴 클레프만',
    publisher: '위키북스',
    publishedDate: '2018-01-31',
    isbn: '978-11-6175-160-2',
    category: '데이터 엔지니어링',
    status: '대출가능',
    description: '확장 가능하고 신뢰할 수 있는 데이터 시스템을 설계하기 위한 원칙과 트레이드오프를 다룬다.',
    coverImage: '9.jpg',
  },
  {
    id: 10,
    title: '인간적인, 너무나 인간적인 UX',
    author: '수잔 와인챙크',
    publisher: '위키북스',
    publishedDate: '2012-05-10',
    isbn: '978-89-6626-131-1',
    category: 'UX',
    status: '대출가능',
    description: '사람의 심리와 행동 원리를 바탕으로 더 나은 사용자 경험을 설계하는 100가지 법칙.',
    coverImage: '10.jpg',
  },
];
