import { RoleRow } from './types';

export const ROLE_ITEMS_DATA: RoleRow[] = [
  {
    id: 1,
    name: '어드민',
    code: 'ADMIN',
    description: '시스템 전체 설정과 사용자 권한을 관리합니다.',
    userCount: 3,
    isSystem: true,
    enabled: true,
    updatedAt: '2026-07-21',
  },
  {
    id: 2,
    name: '워크스페이스 관리자',
    code: 'WORKSPACE_MANAGER',
    description: '소속 워크스페이스의 사용자와 설정을 관리합니다.',
    userCount: 5,
    isSystem: true,
    enabled: true,
    updatedAt: '2026-07-20',
  },
  {
    id: 3,
    name: 'RBAC Member',
    code: 'RBAC_MEMBER',
    description: '기본 업무 화면에 접근하고 데이터를 등록·수정합니다.',
    userCount: 12,
    isSystem: false,
    enabled: true,
    updatedAt: '2026-07-02',
  },
  {
    id: 4,
    name: 'RBAC Viewer',
    code: 'RBAC_VIEWER',
    description: '데이터 조회만 가능하고 수정 권한은 없습니다.',
    userCount: 8,
    isSystem: false,
    enabled: true,
    updatedAt: '2026-06-24',
  },
  {
    id: 5,
    name: '운영자',
    code: 'OPERATOR',
    description: '알림 발송, 코드 관리 등 운영 업무를 수행합니다.',
    userCount: 4,
    isSystem: false,
    enabled: true,
    updatedAt: '2026-07-11',
  },
  {
    id: 6,
    name: '감사자',
    code: 'AUDITOR',
    description: '보안 로그와 발송 로그를 조회하고 감사합니다.',
    userCount: 2,
    isSystem: false,
    enabled: false,
    updatedAt: '2026-05-30',
  },
];
