import { UserRow } from './types';

export const USER_ITEMS_DATA: UserRow[] = [
  {
    id: 1,
    name: 'Swagger Tester',
    email: 'swagger_tester@vanta.local',
    avatarLabel: '?',
    roleId: 2,
    isWorkspaceAdmin: true,
    status: '활성',
    lastLogin: '2026-07-08 14:17:04',
  },
  {
    id: 2,
    name: 'RBAC Member',
    email: 'rbac_member@vanta.local',
    avatarLabel: 'R',
    roleId: 3,
    isWorkspaceAdmin: false,
    status: '휴면',
    lastLogin: '2026-07-02 03:28:38',
  },
  {
    id: 3,
    name: 'RBAC Viewer',
    email: 'rbac_viewer@vanta.local',
    avatarLabel: 'R',
    roleId: 4,
    isWorkspaceAdmin: false,
    status: '비활성',
    lastLogin: '2026-06-24 16:07:06',
  },
  {
    id: 4,
    name: 'Asset',
    email: 'asset@cj.net',
    avatarLabel: '?',
    roleId: 3,
    isWorkspaceAdmin: false,
    status: '활성',
    lastLogin: '2026-07-21 14:39:07',
  },
  {
    id: 5,
    name: 'Genx',
    email: 'genx@cj.net',
    avatarLabel: '?',
    roleId: 3,
    isWorkspaceAdmin: false,
    status: '활성',
    lastLogin: '2026-07-21 16:10:02',
  },
  {
    id: 6,
    name: 'Aion',
    email: 'aion@cj.net',
    avatarLabel: '?',
    roleId: 5,
    isWorkspaceAdmin: false,
    status: '활성',
    lastLogin: '2026-07-21 16:18:16',
  },
  {
    id: 7,
    name: 'Desk',
    email: 'desk@cj.net',
    avatarLabel: '?',
    roleId: 3,
    isWorkspaceAdmin: false,
    status: '활성',
    lastLogin: '2026-06-25 17:12:24',
  },
  {
    id: 8,
    name: 'VFX',
    email: 'vfx@cj.net',
    avatarLabel: '?',
    roleId: 5,
    isWorkspaceAdmin: false,
    status: '활성',
    lastLogin: '2026-07-21 16:16:38',
  },
  {
    id: 9,
    name: '4DX',
    email: '4dx@cj.net',
    avatarLabel: '?',
    roleId: 3,
    isWorkspaceAdmin: false,
    status: '활성',
    lastLogin: '2026-07-21 10:51:56',
  },
  {
    id: 10,
    name: '어드민',
    email: 'admin@cj.net',
    avatarLabel: '어',
    roleId: 1,
    isWorkspaceAdmin: true,
    status: '활성',
    lastLogin: '2026-07-21 16:17:34',
  },
  {
    id: 11,
    name: 'Test1',
    email: 'test1@cj.net',
    avatarLabel: '?',
    roleId: 2,
    isWorkspaceAdmin: true,
    status: '활성',
    lastLogin: '2026-07-20 16:55:03',
  },
  {
    id: 12,
    name: 'SX',
    email: 'sx@cj.net',
    avatarLabel: '?',
    roleId: 2,
    isWorkspaceAdmin: true,
    status: '활성',
    lastLogin: '2026-06-29 17:56:21',
  },
  {
    id: 13,
    name: '감사팀',
    email: 'audit@cj.net',
    avatarLabel: '감',
    roleId: 6,
    isWorkspaceAdmin: false,
    status: '휴면',
    lastLogin: '2026-05-30 09:12:40',
  },
];
